### ISSUE TITLE
Right-clicking shouldn't move slides

### ISSUE THREAD

**Issue by Zimmi48** [xarvh/elm-slides#11]
I am used to debug part of some HTML page by right-clicking some elements I'm interested in. Right now, when I right-click somewhere on the page it has the same effect as when I left-click and it opens the menu. I don't think that this is the ideal behavior.

**Comment by xarvh** [comment]
Sorry, cannot reproduce.
Both on Chrome and Firefox I can right-click and inspect elements normally, page does not move forwards.
