### ISSUE TITLE
Code block indentation doesn't work as expected

### ISSUE THREAD

**Issue by albronca** [xarvh/elm-slides#12]
For example:

```elm
md
    """
    ```ruby
    def do_thing
      do_thing
    end
    ```
    """
```

renders the following layout:
```
def do_thing
   do_thing
     end
```

**Comment by xarvh** [comment]
Weird. Looking into it.

**Comment by xarvh** [comment]
It is a styling issue.
It is resolved already in latest master, I'll update the package now.
