### ISSUE TITLE
Feature request speaker notes

### ISSUE THREAD

**Issue by JordyMoos** [xarvh/elm-slides#16]
I would like to request a feature to have speakers notes. As the notes plugin of revealjs also provides.

https://github.com/hakimel/reveal.js/#speaker-notes

**Comment by xarvh** [comment]
This feature would require using javascript and web workers, which would prevent the library from being published on elm-packages.
More importantly, this feature alone would require more time and effort than has been put so far in the whole library.
However, should you decide that such a feature is worth your own time and effort, I'll be happy to explain you the inner workings of the library.

**Comment by JordyMoos** [comment]
Alright thank you @xarvh! I might get you up on that.

Cheers
