### ISSUE TITLE
Supported way to inject own CSS

### ISSUE THREAD

**Issue by AronNovak** [xarvh/elm-slides#17]
It seems it's supported to inject custom CSS, but it's not documented in the samples.
I'd be glad to create a pull request for that, if a few pointers are given here about where to start.

**Comment by xarvh** [comment]
You are right, it should be in the example.

The way to do it is to create a list of Snippets with rtfeldman/elm-css, and set the `style` Option:
```elm
main = Slides.app

    { slidesDefaultOptions | style = listOfElmCssSnipppets }

    listOfSlides
```

Another possibility is to set `{ slidesDefaultOptions | style = [] }` and modify `index.html` to link to an external css file.

**Comment by xarvh** [comment]
Resolved by https://github.com/xarvh/elm-slides/pull/18/files
