### ISSUE TITLE
Slides module doesn't expose Slide type

### ISSUE THREAD

**Issue by trezona-lecomte** [xarvh/elm-slides#19]
Hey there, because the `Slides` module doesn't expose the `Slide` type alias, consumers of this package can't write type annotations for their slides. 

For example:
```elm
module Main exposing (main)

import Slides exposing (..)

main : Program Never Model Msg
main =
    Slides.app
        Slides.slidesDefaultOptions
        [ welcome ]

welcome =
    html <| div [] [ h1 [] [ text "Into to Elm" ] ]
```
Will compile, but with warnings: `Top-level value languageSummary does not have a type annotation.`. Adding the type annotation `welcome : Slides.Slide` results in a compilation failure: `Slides does not expose Slide. `.

Can you please have a think about exposing the `Slide` type?

Thanks for the package, appreciate your time & effort!

**Comment by xarvh** [comment]
You are 100% right, I completely missed it.
I will likely make it an opaque type, to allow annotations but keep direct instantiation impossible.
I should be able to do this in the next few days.
Thanks for the heads up!

**Comment by trezona-lecomte** [comment]
Sounds great, thanks for the prompt reply 💯

**Comment by xarvh** [comment]
Fixed by https://github.com/xarvh/elm-slides/commit/315d388bc9368dab37ab07d5da6e5834daccb681

**Comment by trezona-lecomte** [comment]
Thanks a lot @xarvh, appreciate it!
