### ISSUE TITLE
elm 0.19 ready

### ISSUE THREAD

**Issue by eratio08** [xarvh/elm-slides#20]
Hey,

could you re-publish the package so it is compatible to elm 0.19?

Thank you! Great work!

**Comment by xarvh** [comment]
Thank you!
I was working on a port when Elm 0.19 came out, and got stuck somewhere, I'll have another look. =)

**Comment by xarvh** [comment]
Done.
I didn't have much time to sink into it, and the changes to Css and Browser were a pain, I hope I got all bugs.

Closed by https://github.com/xarvh/elm-slides/pull/21

**Comment by eratio08** [comment]
Thank you!!
