### ISSUE TITLE
html expecting Html.styled.Html

### ISSUE THREAD

**Issue by exoji2e** [xarvh/elm-slides#22]
Hi I can't figure out how to use the `Slides.html` function:

```
module Main exposing (..)

import Html exposing (..)
import Slides exposing (html, slidesDefaultOptions)


main =
    Slides.app
        slidesDefaultOptions
        [ intro_slide ]


intro_slide =
    Slides.html <|
        div []
            [ h1 []
                [ text "Hello World!"
                ]
            ]

```

Gives me the following compile error:

```
-- TYPE MISMATCH ------------------------------------------------------ main.elm

I cannot send this through the (<|) pipe:

14|     Slides.html <|
15|>        div []
16|>            [ h1 []
17|>                [ text "Hello World!"
18|>                ]
19|>            ]

The argument is:

    Html msg

But (<|) is piping it a function that expects:

    Html.Styled.Html Slides.Msg

```

Where does the Html.Styled.Html type come from? Are you using an old version of `elm/html`?

**Comment by xarvh** [comment]
`Html.Styled` is provided by `https://package.elm-lang.org/packages/rtfeldman/elm-css/latest/`.
However I notice now that the documentation does not mention it, so your confusion is very understandable.

I will amend the docs in the next release (which, TBH, I don't know when I'll do).
Thanks for the heads up! =)

**Comment by xarvh** [comment]
Fixed in https://github.com/xarvh/elm-slides/commit/0daa5f5e1c70520e2bfd44bf07b8385d716ac490
