### ISSUE TITLE
Animation of objects

### ISSUE THREAD

**Issue by nova-nowiz** [xarvh/elm-slides#26]
Do you think it would be possible to have animations of objects like images and text in this library?
What I mean is having within one slide sequential animations as in PowerPoint or Keynote.

This would be a killer feature compared to reveal.js that only has this feature (without smooth animations) as a plugin.

Free placement of objects would be a requirement for this to work like PowerPoint or Keynote, but this free placement would also be very very interesting on its own.

I'll try to work on it when I have some time, if you have suggestions for the format or if you think it is simply not possible, please tell me!

**Comment by xarvh** [comment]
I think it should be possible.

I assume that the most generic way would be something like:

```elm
htmlAnimatedFragments : List (Float -> Html Msg) -> Slide
```

where the `Float` argument would be a number form 0 (animation start) to 1 (animation end).

Then I assume there would be some helper functions that could be used to render the things you had in mind.

**Comment by nova-nowiz** [comment]
That makes sense! I'll take a go at it when I have some time ;)
Do you want me to keep you updated or just do a pull request once I'm finished?

**Comment by xarvh** [comment]
Might be useful to discuss the API before embarking in the implementation.

**Comment by nova-nowiz** [comment]
Oh yes sorry, I'm really new to open software participation and software participation in general.
So, what you were proposing is a way to have a slide from a set of functions that the user puts as a list. That might be unpractical, but would be very customizable and we could have functions to build these functions with just html, start and end values as parameters and as an output the actual `Float -> Html Msg` function:
```elm
type Position
     = Position {x : Int, y : Int}

htmlAnimatedFragment : Html Msg -> Position -> Position -> (Float -> Html Msg)
htmlFragment : Html Msg -> (Float -> Html Msg) -- For a non animated fragment in otherwise animated fragments
```
Also, for the Slide data structure, I've seen that it was only containing a `List (Html Msg)` which might not be enough for this feature, however, switching this to `List (Float -> Html Msg)` would be quite painless (at least for building the slide object) by modifying htmlFragments like this:
```elm
htmlFragments : List (Html Msg) -> Slide
htmlFragments htmlNodes =
    Slide { fragments = (\f -> htmlNodes) }
```
This seems to be required to be able to animate each and every slide fragments while we go through the slides.
But it might involve reimplementing some animation functionalities for slides.
I didn't read the code for now as I have only very limited time, but I hope the changes are not that severe.

**Comment by xarvh** [comment]
No stress. =)

It might be useful to start from the end.
How would you like to *use* the library? How would you like to declare your animation?

Write the slides you would like to be able to express, with all the animations you would like to put in.

Don't worry about the content of `Slide`, it's an opaque type anyway.

**Comment by nova-nowiz** [comment]
Hey, thanks for the response!
I really needed the "No stress. =)" part of it x)
It was also very useful to start from the end

So, what I really want to do is use this library as my main way of doing slides on Linux, because there are only web alternatives like reveal.js, deck.js, and others and I really really don't want to do some js to build my slides. Slid.es which is the reveal.js editor doesn't have animations apart from the auto-animate transition which is really cool but which does not offer the same granularity as PowerPoint of Keynote's animations which are done on one slide.

Other alternatives would be openoffice impress but apparently, it has some problems with embedded media, making it very slow. There is also Beamer, which is really good for scientific topics, but which doesn't cut it for presentations of other kinds.

The level of animations I'm looking for are the ones from the evergreen talk which really blew my mind, I've asked Mario (the presenter) and it was done in Keynote as it has the smoothest experience for animating and changing stuff in general.


From what I see there are three main things that this proprietary software does in terms of animations: You can do "Build-in" "Action" and "Build-out" animations.
You can modify the build order of every animation. Each animation can be launched either with a mouse click or with the previous animation with a delay or after it with also a delay.
Animations can be attached to different objects. objects can have multiple animations, and they can play in whatever order defined by the user.

I don't know if this would be hard in elm, but it seems to be.
The user would have to build static objects with html (for example with elm-ui) or markdown. These objects should be static in definition in my opinion (but that might be wrong, I don't really know). Then, the user would place them on the slide and give the animations of the slide.
So I guess something like this:
```elm
type Slide
    = Slide SlideRaw


type alias SlideRaw =
    { objects : Dict String Object -- Objects can be in any order and have a unique string id

    -- Animations are in order and are applied on an object (which is chosen by id) after a trigger
    , animations : List ( Trigger, Animation, String )
    }


type Object
    = Object ObjectRaw


type alias ObjectRaw =
    { html : Html Msg
    , position : Position
    , dimension : Dimension
    }


type Animation
    = Animation (Object -> Float -> Object)


type Trigger
    = Click
    | WithPrevious Float
    | AfterPrevious Float


slideBuilder : List Object -> List Animation -> Slide


objectBuilder : Html Msg -> Dimension -> Position -> Object


scaleAnimation : Trigger -> String -> Float -> ( Trigger, Animation, String )


relativeDimensionAnimation : Trigger -> String -> Dimension -> ( Trigger, Animation, String )


absoluteDimensionAnimation : Trigger -> String -> Dimension -> ( Trigger, Animation, String )


relativePositionAnimation : Trigger -> String -> Position -> ( Trigger, Animation, String )


absolutePositionAnimation : Trigger -> String -> Position -> ( Trigger, Animation, String )


main =
    Slides.app
        Slides.slidesDefaultOptions
        [ slide1
        , slide2
        ]


slide1 : Slide
slide1 =
    slideBuilder
        [ ( "Object1", object1 ) -- Dimension and position already defined in the object1 function
        , ( "Object2", object2 { x = 100, y = 200 } ) -- Position not defined in the object2 function
        ]
        [ scaleAnimation Click "Object1" 0.5
        , absolutePositionAnimation (WithPrevious 0.5) "Object2" { x = 50, y = 50 }
        , relativePositionAnimation (AfterPrevious 1) "Object1" { x = -50, y = 100 }
        ]


object2 : Position -> Object
object2 =
    objectBuilder
        -- elm-ui or html stuff here
        { w = 200, h = 100 }
        -- the position is not given so it can be given in the slideBuilder function
```
It took a long time but I guess I would really be happy with this setup, it seems very modular.
One thing that I'm not a fan of is the String type for the id, I would like to use an `Id` type but I don't know if it can be used as a key in a dictionary, so that's why!
I hope you like my idea and sorry for the **very** long post

**Comment by nova-nowiz** [comment]
just to clarify the `Position` and `Dimension`, they are just type aliases to a record in the above code.

**Comment by xarvh** [comment]
I don't think elm-slides should do what Keynote does.

The thing is, elm-slides exist to quickly put together a presentation that looks decent, using mostly text.

If you want to be able to do everything that Keynote does, probably expressing it with code is not the best approach, you probably want a visual editor instead than entering coordinate values manually.

Consider that in your `object2` declaration you will be pretty much writing complex SVG manually.
I don't want to stifle your enthusiasm, but we should think whether code is the best way to express graphics.

**Comment by nova-nowiz** [comment]
That's true, I thought about it as well.
Code is not the best way.
A graphical editor is a far better way to place elements, but I think that designing each element with the flexibility that elm-ui (or html+css) gives would be really good.
I could argue that reveal.js succeeded in having an online editor for building the slides out while still remaining a library, however, I do understand that this brings complications that don't align with the goal of this library.
Should this issue be closed?

Ps: I don't really understand what the SVG part of your comment means. Is it the fact that for every object you have an html part or is it related to specifying the position and dimension for each of them or both?

**Comment by xarvh** [comment]
Building an editor would be interesting, but feels like it would be a lot of work.
Also, once you have an editor, would it make sense to use a library such as elm-slides?

I was thinking about writing SVG directly in Elm rather than referencing it as an image file.

I will close the issue for the time being, but I can reopen it if there are other ideas. =)
